"""empty message

Revision ID: 69934978e86d
Revises: 9446768daa80
Create Date: 2022-01-29 13:11:09.931414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69934978e86d'
down_revision = '9446768daa80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_gameDetails_match_id'), 'gameDetails', ['match_id'], unique=False)
    op.drop_index('ix_gameDetails_match_id', table_name='gameDetails')
    op.create_index(op.f('ix_selectedSquad_match_id'), 'selectedSquad', ['match_id'], unique=False)
    op.drop_index('ix_selectedSquad_match_id', table_name='selectedSquad')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_selectedSquad_match_id', 'selectedSquad', ['match_id'], unique=False)
    op.drop_index(op.f('ix_selectedSquad_match_id'), table_name='selectedSquad')
    op.create_index('ix_gameDetails_match_id', 'gameDetails', ['match_id'], unique=1)
    op.drop_index(op.f('ix_gameDetails_match_id'), table_name='gameDetails')
    # ### end Alembic commands ###
